#include "accumulators_extension.hpp"

#include "statistics/rolling_window.hpp"
#include "statistics/rolling_sum.hpp"
#include "statistics/rolling_count.hpp"
#include "statistics/rolling_mean.hpp"
#include "statistics/count.hpp"
#include "statistics/p_square_quantile.hpp"
#include "statistics/moment.hpp"
#include "statistics/min.hpp"
#include "statistics/max.hpp"
#include "statistics/sum.hpp"
#include "statistics/kurtosis.hpp"
#include "statistics/median.hpp"
#include "statistics/mean.hpp"
#include "statistics/skewness.hpp"
#include "statistics/variance.hpp"
#include "statistics/rolling_moment.hpp"
#include "statistics/density.hpp"
#include "statistics/sum_kahan.hpp"
#include "statistics/tail.hpp"
#include "statistics/pot_quantile.hpp"

